### ISSUE TITLE
Incorrect Date selected? 

### ISSUE THREAD

**Issue by RNUK** [mmick66/CalendarView#7]
I have implemented the code provided and there seems to be a mismatch between the dates on the calendar and the dates selected?

The following code:

```
    func calendar(_ calendar: CalendarView, didSelectDate date : Date, withEvents events: [EKEvent]) {

        if events.count > 0 {
            let event : EKEvent = events[0]
            print("We have an event starting at \(event.startDate) : \(event.title)")
        }
        print("Did Select: \(date) with Events: \(events.count)")

    }
```

returns the following to the console when 4th July is selected?

**We have an event starting at 2016-10-09 20:25:00 +0000 : Raiders vs Chargers (Week 5)
Did Select: 2016-07-04 00:00:00 +0000 with Events: 1**

I guess that the events array is not being fully populated so the indexes are misaligned. Any idea what may cause this?

**Comment by hamidgh** [comment]
I got the same issue. I select a date like 10/06/2016 but it returns the value of yesterday 10/05/2016

**Comment by mmick66** [comment]
I created a custom calendar event type that is created after accounting for the time difference that was due to timezones.

**Comment by hamidgh** [comment]
Unfortunately it's not fixed yet. I still has the issue when I select a date, it returns a day before the date that I selected.

**Comment by mmick66** [comment]
Did you checkout the latest code? (sorry, I have to ask)... Please give me an example because it is not happening for me... Tell me your start and end date and which one you are selecting, and then paste the log like so:

You have an event starting at 2017-03-17 00:00:00 +0000 : Saint Patrick’s Day
Did Select: 2017-03-17 00:00:00 +0000 with Events: 1

It would also help if you could zip the project and drop it here...
